import { Meteor } from 'meteor/meteor';
import { HTTP } from 'meteor/http';
import { State } from '/imports/global/api/State.js';

/**
 * Contains all functionality relating to TheMovieDB API.
 */
const TheMovieDB = {
  /**
   * Accepts a search query string and constructs an encoded URI
   * that can be used to search TheMovieDB for movies.
   *
   * @param { String } query
   * @return { String } A constructed '/search' URI.
   */
  handleSearchURI: (query) => {
    const { base_uri, key_v3 } = Meteor.settings.public.themoviedb;
    const encodedQuery = encodeURI(query);
    return `${base_uri}/search/movie?api_key=${key_v3}&query=${encodedQuery}`;
  },

  /**
   * Creates a non-blocking HTTP request to TheMovieDB '/search' endpoint
   * to search TheMovieDB for movies.
   *
   * @param { String } endpointURI generated by the TheMovieDB.handleSearchURI() function.
   * @return { GET } requests movies data from TheMovieDB '/search' endpoint.
   */
  searchTheMovieDB: (endpointURI) => {
    State.set.querying(true);

    return HTTP.call('GET', endpointURI, {}, (error, result) => {
      State.set.querying(false);

      if (error) {
        throw new Meteor.Error('Error requesting data from TheMovieDB', error);
      }

      State.set.status('searchTheMovieDB');
      State.set.tmdbSearchResults(result);
    });
  },
  /**
   * Accepts a movieID string and constructs an encoded URI that can
   * be used to get a movies credits data from TheMovieDB.
   *
   * @param { String } movieID
   * @return { String } A constructed '/credits' URI.
   */
  handleCreditsURI: (movieID) => {
    const { base_uri, key_v3 } = Meteor.settings.public.themoviedb;
    return `${base_uri}/movie/${movieID}/credits?api_key=${key_v3}`;
  },

  /**
   * Creates a non-blocking HTTP request to TheMovieDB '/credits' endpoint
   * to retrieve a movies credits data.
   *
   * @param { String } endpointURI generated by the TheMovieDB.handleCreditsURI() function.
   * @return { GET } requests movies data from TheMovieDB '/credits' endpoint.
   */
  getCreditsData: (creditsURI) => {
    State.set.querying(true);

    return HTTP.call('GET', creditsURI, {}, (error, result) => {
      State.set.querying(false);

      if (error) {
        throw new Meteor.Error('Error requesting data from TheMovieDB', error);
      }

      State.set.status('getCreditsData');
      State.set.creditsData(result);
    });
  },

  clearTMDBSearchResults: () => {
    State.set.status('clearTMDBSearchResults');
    State.clear.tmdbSearchResults();
  },

  /**
   * Stylizes the data returned by TheMovieDB API to better match our needs.
   *
   * @param { Object } data retrieved from TheMovieDB API.
   * @return { Method } Call to set the rawData state.
   */
  setRawData: (rawData) => {
    if (!rawData) {
      throw new Meteor.Error('422', 'No raw movie data found');
    }

    const {
      id: tmdb_id,
      backdrop_path: banner,
      original_title: title,
      overview: description,
      poster_path: poster,
      release_date,
    } = rawData;

    const data = {
      banner: banner ? `https://image.tmdb.org/t/p/w780${banner}` : '/images/placeholder-banner.jpg',
      description,
      poster: poster ? `https://image.tmdb.org/t/p/w300_and_h450_bestv2${poster}` : '/images/placeholder-poster.jpg',
      title,
      tmdb_id,
      release_date,
      release_year: release_date.split('-').slice(0, 1)[0],
    };

    State.set.status('setRawData');

    return State.set.rawData(data);
  },

  /**
   * Creates an array of objects to be submitted to the Mongo collection
   * once all data has been gathered and stylized. This the primary way
   * our data gets into the app.
   *
   * @param { String } Accepts several types including:
   *                   - "DVD"
   *                   - "Other"
   *                   - "Blu-Ray"
   *                   - "Digital Download"
   * @param { String } A description of where this movie is currently located,
   *                   useful for keeping track of the media items whereabouts.
   * @return { Method } Call to set the submissionData state.
   */
  addToSubmisionData: (type, location) => {
    const rawData = State.get.rawData();
    const creditsData = State.get.creditsData();
    const currentsubmissionData = State.get.submissionData();

    if ((rawData && !rawData) || (creditsData && !creditsData)) {
      return;
    }

    const { cast, crew } = creditsData.data;

    const submissionData = [
      ...currentsubmissionData,
      {
        location,
        movie_type: type,
        ...rawData,
        cast: cast.slice(0, 10),
        crew,
      },
    ];

    State.clear.rawData();
    State.clear.creditsData();

    State.set.status('addToSubmisionData');

    return State.set.submissionData(submissionData);
  },
};

export { TheMovieDB };
